service:
  name: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  
functions:
  createAuction:
    handler: src/handlers/create-auction.handler
    events:
      - http:
          method: POST
          path: /auction
