service:
  name: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iamRoleStatements:
    - ${file(aws/iam/AuctionsTableIAM.yml):AuctionsTableIAM}
  
functions:
  createAuction:
    handler: src/handlers/create-auction.handler
    events:
      - http:
          method: POST
          path: /auction

  getAuctions:
    handler: src/handlers/get-auctions.handler
    events:
      - http:
          method: GET
          path: /auctions

  getAuction:
    handler: src/handlers/get-auction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}

  placeBid:
    handler: src/handlers/place-bid.handler
    events:
      - http:
          method: PATCH
          path: /auction/{id}/bid

resources:
  Resources:
    AuctionsTable: ${file(aws/resources/AuctionsTable.yml):AuctionsTable}

custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn