service:
  name: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
    AUCTIONS_BUCKET_NAME: ${self:custom.AuctionsBucket.name}
  iamRoleStatements:
    - ${file(aws/iam/AuctionsTableIAM.yml):AuctionsTableIAM}
    - ${file(aws/iam/AuctionsBucketIAM.yml):AuctionsBucketIAM}
  
functions:
  createAuction:
    handler: src/handlers/create-auction.handler
    events:
      - http:
          method: POST
          path: /auction
          authorizer: ${self:custom.authorizer}

  getAuctions:
    handler: src/handlers/get-auctions.handler
    events:
      - http:
          method: GET
          path: /auctions
          authorizer: ${self:custom.authorizer}

  getAuction:
    handler: src/handlers/get-auction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
          authorizer: ${self:custom.authorizer}

  placeBid:
    handler: src/handlers/place-bid.handler
    events:
      - http:
          method: PATCH
          path: /auction/{id}/bid
          authorizer: ${self:custom.authorizer}

  uploadAuctionPicture:
    handler: src/handlers/upload-auction-picture.handler
    events:
      - http:
          method: PATCH
          path: /auction/{id}/picture
          authorizer: ${self:custom.authorizer}

  processAuctions:
    handler: src/handlers/process-auctions.handler
#    events:
#      - schedule: rate(1 minute)

resources:
  Resources:
    AuctionsTable: ${file(aws/resources/AuctionsTable.yml):AuctionsTable}
    AuctionsBucket: ${file(aws/resources/AuctionsBucket.yml):AuctionsBucket}
    AuctionsBucketPolicy: ${file(aws/resources/AuctionsBucket.yml):AuctionsBucketPolicy}

custom:
  authorizer: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:serverless-auth0-authorizer-${self:provider.stage}-auth
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  AuctionsBucket:
    name: auctions-bucket-d3j428-${self:provider.stage}